package get.wordy.app.settings;

public enum Setting {
    LANGUAGE,
    DISPLAY_ON_STARTUP,
    HIDE_WHEN_MINIMIZE,
    AUTO_RUN_ON_STARTUP,
    SOUND,
    ANIMATION,
    ANIMATION_AND_SOUND,
    NUMBER_OF_CARDS_IN_EXERCISE,
    NUMBER_OF_REPETITIONS,
    NUMBER_OF_CARDS_TO_LEARN,
    SCHEDULER_ENABLED,
    SCHEDULER_TIME_FREQUENCY,
    FONT,
    DICTIONARY_NAME
}
